services:
  server:
    container_name: server
    image: ${SERVER_DOCKER_IMAGE:?error}
    restart: always
    ports:
      - 8000:8000
    env_file: .env
    networks:
      - app_network
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: database
    image: postgres
    restart: always
    volumes:
      - pg:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

volumes:
  pg:

networks:
  app_network:
    driver: bridge
    external: true
